CREATE DATABASE IF NOT EXISTS pedidosdb;
USE pedidosdb;

CREATE TABLE IF NOT EXISTS produtos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	tipo ENUM ('prato', 'bebida') NOT NULL,
	preco DECIMAL(10, 2) NOT NULL

);

CREATE TABLE IF NOT EXISTS pedidos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome_cliente VARCHAR(100) NOT NULL
	mesa INT NOT NULL,
	status VARCHAR (20) NOT NULL DEFAULT 'EM PREPARO'
);

CREATE TABLE IF NOT EXISTS itens_pedido (
	id INT AUTO_INCREMENT PRIMARY KEY,
	pedido_id INT NOT NULL,
	produto_id INT NOT NULL,
	quantidade INT NOT NULL,
	FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
	FOREIGN KEY (produto_id) REFERENCES produtos(id)
);

CREATE TABLE IF NOT EXISTS usuarios(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL
);
